services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/positrom
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=positrom2.settings
